version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      day: "sunday"
  # Maintain dependencies for go lang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
      day: "sunday"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      day: "sunday"
  # Maintain dependencies for dev docker
  - package-ecosystem: "docker"
    directory: "/test/migrator-dev"
    schedule:
      interval: "weekly"
      time: "06:00"
      day: "sunday"