language: go

env:
  - DB=postgresql

services:
  - postgresql

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database \"migrator-test\" -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -f test/create-test-tenants.sql -U postgres -d migrator-test; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then cp test/migrator-postgresql.yaml test/migrator.yaml; fi"

script:
  - go test -v
