language: go
services:
- docker
go:
- '1.16'
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker-compose -f test/docker-compose.yaml up -d
script:
- "./coverage.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: Bt928QX5q5q27iAGQQ/8snkEJAsV5ODHzO4pXqV42tNtrF1T0Yi+5JaUnED+v+1ROLv488Xy1Wgt9qLilIVFgo4AIsa6Z2vziWnEffwtehiSNybqnI5yHGFIpYj4JvvUP6oLNX3fcYTykmeVWouVtWrhJ2GoeWp5SeNLXqbTt6b8BJ1ewYyAiaJLoHB9DoiG9o+3TUErYtz9LJHI64s8SPvh3u39Q0zkN2K3egAtPL7H2h1LsIJu6sN6w1QGO/6bXoEhZAhQUeDlqXJrzAV1G2SgCB+QXYWC8XYz2TxKumEF4484R8yABH1soGK4FC8fCEy8s5AcFITyqzyrnZFD7ZyRVCx0fWAsVHTJ5tvnD2Ezxyb1vfOWkKKeAVnOHGgK+kMKol6qDVJapHbPTYZpyY2JQrsZtEzSSDKuhDamaeEBTxhlVIDKswQhzuX7IpemGTm64LbU4CjeVB2EORv4uMs1U6fH0gwCl1DySO4xpbtNa7hwfk12B+nx7DJfNwejvHZ5Cb10F0LYGKWYQtddRX/cQeLl8e4OPXiglO7cnXh4p+xkQxEWF7OLisl26bDex6YOLzR3tca3F29jvHKr35Qu62mtxfhUuvfCgOiQYo/C3RhyGANr37px78RgOgFpeT/22I/wMk6XZDadCgDPYEktHB33m43Eyqu1ZysjZQA=
  - secure: e1xqq9XDYNGo+70NyPujD7+Iu1SolL7Ze0MaWRYyJ4Jts4MxEo2iooS8P5vjMgmgq/EvN0wJsVGZNMOYL/6DDA4kzaoqIY17uvoj4eh/BVvmFKveaal2io7bZLxUx6gLfD8e1oHDPL3lxS9mLtsuSZbJo9lDVJkSPrNwgvhZw/FTlsU7YiweFjxUstbVqPDseDVF8QhMrgtbWZ6Sz93x3QZ5eaALgcOR09Hrbg9M3T9wCFJEeWQ+NJ5SYnZdO1N+J3NjjFmSBpXUwIrlNRNyodA4+l4T9uTn6lIY5ShU+kMD4MOzG/MI/H/acMQ+z7dvvjKqgucDAgslvOfFMBXOmmUZJxx5r6EktfnOI2FdrRQs2VnwGfWHVzof8nKV6JVxPj4FfS4gnNUP3zLXwa5qSpq9kgHbWAEuWhmeV1mdYBbX1NOtuGFqFkpIu+oQgOZGfCn7TgYqaxq+icjVNaRQgPc9xT66cf5UuDNCflP572TyrtNQOs3rAsZSTyB38Bclef4SAFTKvHR7iq7aDAe59eFvkaUhe8xHjMFo9t9ysGeHkgI3ybABUh6Fcz+G6nN7ed1iZpBP0w+2u9UKEMjTn+sI9oT59mY8nz5sl8YowFO3UBwuvPE0ZwXWHlOFfIW041YzR9eiu1JDqwWih9HprlsEaMbbZfOTLV2J08XByjM=
