language: go

addons:
  postgresql: '9.6'

env:
  - DB=postgresql
  - DB=mysql

services:
  - postgresql
  - mysql

go:
  - "1.11"
  - "1.12"
  - "1.13"

before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -U postgres -c 'create database migrator_test'; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -U postgres -d migrator_test -f test/create-test-tenants.sql; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'create database migrator_test'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -D migrator_test < test/create-test-tenants.sql; fi"
  - sh -c "cp test/migrator-$DB.yaml.travis test/migrator.yaml"

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
