language: go
services:
- docker
go:
- '1.17'
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker-compose -f test/docker-compose-it.yaml up -d
script:
- "./coverage.sh"
- "./test/http-integration-tests.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)

