name: Dependabot build and test

on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        go: [ '1.16', '1.15', '1.14' ]
    name: Go ${{ matrix.go }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Start docker-compose services
      run: docker-compose -f test/docker-compose.yaml up -d

    - name: Build and test migrator
      env:
        AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      run: ./coverage.sh

    - name: Run HTTP integration tests
      run: ./test/http-integration-tests.sh

    - uses: codecov/codecov-action@v2.0.2
